### PR TITLE
Update symfony di dependency  

### PR DESCRIPTION
**Pull request by lascaps**
update symfony/dependency-injection requirement

### CODE REVIEW

**Comment by jsoumelidis** [comment]
Thnx @xvct!

**Comment by icanhazstring** [comment]
@jsoumelidis is it possible to get a new patch version for this?
Edit: Nevermind you have tagged it, but it doesn't show on packagist

**Comment by jsoumelidis** [comment]
Hello @icanhazstring, i did a packagist update. You should be able to get v0.4.1 now :)

**Comment by icanhazstring** [comment]
That was a quick one. Thank you 🙏

**Pull request merged**
